name: Build assets for a Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            release_asset: dotter-x86_64-unknown-linux-musl.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            release_asset: dotter-x86_64-pc-windows-msvc.zip
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release --locked --verbose --target ${{ matrix.target }}
      - name: Pack for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          RELEASE_DIR=dotter-${{ matrix.target }}
          mkdir $RELEASE_DIR
          cp -r target/${{ matrix.target }}/release/dotter -t $RELEASE_DIR
          cp -r completions -t $RELEASE_DIR
          tar -zcvf ${{ matrix.release_asset }} -C $RELEASE_DIR .
      - name: Pack for Windows
        if: matrix.os == 'windows-latest'
        run: |
          RELEASE_DIR=dotter-${{ matrix.target }}
          mkdir $RELEASE_DIR
          cp -r target/${{ matrix.target }}/release/dotter.exe -t $RELEASE_DIR
          cp -r completions -t $RELEASE_DIR
          zip -r ${{ matrix.release_asset }} $RELEASE_DIR
      - name: Upload asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.release_asset }}
